name: Super Linter

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  super_linter:
    name: Super Linter
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run super-linter
        uses: super-linter/super-linter/slim@v7
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}